config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'landing#index'
  get 'landing/index'
  resources :books do
    resources :borrows, only: [:new, :create, :index, :show, :update]
    get 'reza'
  end
  resources :users do
    resources :borrows, only: [:index, :destroy, :show, :update]
  end
  resources :borrows

  namespace :users do
    get 'authors/new', action: 'new'
  end
  namespace :books do
    get 'search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @books = Book.order('created_at desc').limit(4)
    @authors = User.joins(:role).where(roles: { name: 'author' }).order('updated_at desc').limit(4)
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.erb
<div class="ui padded grid">
  <div class="ui row">
    <h2 class="ui header" style="width: 100%; padding: 0em 1rem">
      <%= image_tag "books.png", class: "ui small image" %>
      <div class="content">
        Latest <%= link_to "Books", books_path %>
      </div>
      <div class="ui right floated basic segment" style="margin: 0em !important; padding: 0em !important;">
        <%= link_to "More", books_path, class: "ui green button" %>
      </div>
    </h2>
    <div class="ui four cards" style="margin: 0">
      <% @books.each do |book| %>
        <%= render 'books/card', {book: book} %>
      <% end %>
    </div>
  </div>
  <div class="ui row">
    <div class="ui grid container">
      <div class="ui eight wide column">
        <h2 class="ui header">
          <%= image_tag "author.png" %>
          <div class="content">
            Latest <%= link_to "Authors", users_path %>
          </div>
        </h2>
        <div class="ui horizontal cards">
          <% @authors.each do |author| %>
            <%= render('users/card', {user: author}) %>
          <% end %>
        </div>
      </div>
      <div class="ui eight wide column">

      </div>
    </div>
  </div>
</div>