config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'landing#index'
  get 'landing/index'
  resources :books do
    resources :borrows, only: [:new, :create, :index, :show, :update]
    get 'reza'
  end
  resources :users do
    resources :borrows, only: [:index, :destroy, :show, :update]
  end
  resources :borrows

  namespace :users do
    get 'authors/new', action: 'new'
  end
  namespace :books do
    get 'search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # constants
  MAX_BORROW_ITEM = 4

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ,:confirmable

  # associations
  has_many :borrows
  has_many :borrowed_books, through: :borrows, class_name: "Book", source: "book"
  has_and_belongs_to_many :books, join_table: "authors_books", class_name: "Book"
  belongs_to :role
  delegate :permissions, to: :role, allow_nil: true
  has_one_attached :avatar

  # validations
  validates :first_name, :last_name, :nickname, length: { maximum: 50 }
  validates :first_name, :last_name, :email, :phone, :password, presence: true
  validates :email, format: { with: /\A([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-]+)\.([a-zA-Z]{2,5})\z/, message: 'please provide valid email!' }
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: 'Please provide valid name' }
  validates_date :birth_date, before: -> { Date.today }, before_message: 'must be before today'
  validates :phone, format: { with: /\A\+\d{12}\z/ }, length: { is: 13 }
  validates :avatar, blob: { content_type: :image }

  def initialize(args)
    #
    # do whatever, args are passed to super
    #
    args[:role_id] = Role.where(name: 'student').first.id if args && args['role_id'].nil?
    super
  end

  def method_missing(method_id, *args)
    if (match = matches_dynamic_role_check?(method_id))
      tokenize_roles(match.captures.first).each do |check|
        return role.name.downcase == check
      end
      false
    elsif (match = matches_dynamic_perm_check?(method_id))
      return true if !permissions.nil? && permissions.find_by_name(match.captures.first)
    else
      super
    end
  end

  def respond_to_missing?(method_name, include_private = false)
    matches_dynamic_role_check?(method_name) || super
  end

  def signed_in?
    !role.nil?
  end

  def author?(book_id)
    if is_an_author?
      !books.where({ books: { id: book_id } }).empty?
    elsif can_edit_book?
      true
    else
      false
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def can_borrow_book?(book_id)
    borrows.where(return_date: nil).count < MAX_BORROW_ITEM && permissions.find_by_name('borrow_books')
  end

  def can_update_book?(book_id)
    permissions.find_by_name('update_books') || books.where(id: book_id)[0]
  end

  def can_update_user?(user_id)
    permissions.find_by_name('update_users') || user_id == id
  end

  private

  def matches_dynamic_role_check?(method_id)
    /^is_an?_([a-zA-Z]\w*)\?$/.match(method_id.to_s)
  end

  def tokenize_roles(string_to_split)
    string_to_split.split(/_or_/)
  end

  def matches_dynamic_perm_check?(method_id)
    /^can_([a-zA-Z]\w*)\?$/.match(method_id.to_s)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super do
      sign_in(resource) if resource.errors.empty?
    end
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :phone, :birth_date, :password, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    if params[:user][:password].present?
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname, :phone, :birth_date, :current_password, :email, :avatar, :password, :password_confirmation])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname, :phone, :birth_date, :current_password, :email, :avatar])
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :can_show_profile?, only: [:show]

  def index
    @users = if current_user
               User.all
             else
               User.joins(:role).where(role: {name: 'author'})
             end
  end

  def show
    @user = User.find(params[:id])
    @borrows = current_user.borrows.where(return_date: nil).joins(:book)
  end

  def new
    @user = User.new
    @roles = Role.select(:name, :id)
    default_role = Role.where(name: 'author').select(:name, :id)
    @user.role_id = default_role[0].id
  end

  def create
    # Create the user from params
    @user = User.new(user_params)
    if @user.save
      # Deliver the signup email
      # UserMailer.send_signup_email(@user).deliver
      redirect_to(@user, notice: 'User created')
    else
      render action: 'index'
    end
  end

  private

  def users_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :phone, :birth_date, :password, :email, :role_id)
  end

  def can_show_profile?
    unless params[:id] && numeric?(params[:id]) && (User.joins(:role).where(id: params[:id], roles: {name: 'author'})[0] || current_user.id == params[:id].to_i)
      redirect_to request.referer || request.base_url, notice: 'This user doesn\'t have public profile!'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.erb
<div class="card">
  <div class="image">
    <%= image_tag avatar_url(user.id), class: "ui image", style: "margin: 0" %>
  </div>
  <div class="content">
    <div class="header">
      <%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id) %></div>
    <div class="meta">
    </div>
    <div class="description">
      <%= user.books.length == 1 ? "Book" : "Book".pluralize %>:
      <div class="ui bulleted list">
        <% user.books.each do |book| %>
          <%= link_to "#{book.title}", book_path(book.id), class: "item" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="ui link cards">
  <% @users.each do |user| %>
    <%= render 'card', {user: user} %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= content_for :styles do %>
  <style>
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>
<% end %>
<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <div class="content">
        Register an account
      </div>
    </h2>
    <%= form_with model: @user, url: users_path, html: { class: 'ui large form' } do |f| %>
      <div class="ui stacked left aligned segment">
        <div class="field">
          <%= f.label :first_name, 'First Name' %>
          <%= f.text_field :first_name, required: true, placeholder: 'First Name' %>
        </div>
        <div class="field">
          <%= f.label :last_name, 'Last Name' %>
          <%= f.text_field :last_name, required: true, placeholder: 'Last Name' %>
        </div>
        <div class="field">
          <%= f.label :nickname, 'Nickname' %>
          <%= f.text_field :nickname, placeholder: 'Nickname' %>
        </div>
        <div class="field">
          <%= f.label :email, 'E-mail' %>
          <%= f.email_field :email, required: true, placeholder: 'Email' %>
        </div>
        <div class="field">
          <%= f.label :phone, 'Phone' %>
          <%= f.phone_field :phone, required: true, placeholder: 'Phone' %>
        </div>
        <div class="field">
          <%= f.label :birth_date, 'Birth Date' %>
          <%= f.date_field :birth_date, required: true, placeholder: 'Birth Date' %>
        </div>
        <div class="field">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, required: true, placeholder: 'Password' %>
        </div>
        <div class="field">
          <%= f.label :role_id, 'Role' %>
          <div class="ui fluid disabled search selection dropdown deny-addition">
            <%= f.hidden_field :role_id, required: true, placeholder: 'Role', value: @user.role_id %>
            <i class="dropdown icon"></i>
            <div class="default text">Role</div>
            <div class="menu">
              <% @roles.each do |r| %>
                <div class="item" data-value="<%= r.id %>"><%= r.name %></div>
              <% end %>
            </div>
          </div>
        </div>

        <%= f.submit "Register", class: 'ui fluid large teal submit button' %>
      </div>
    <% end %>
  </div>
</div>

<script>
    $(".ui.deny-addition.dropdown").dropdown();
    $(".ui.calendar").calendar({type: 'date',})
</script>

app/views/users/show.html.erb
<div class="ui grid container">
  <div class="ui three wide column">
    <%= image_tag avatar_url(@user.id), style: "width: 100%" %>
    <div class="ui list">
      <% if authenticated? %>
        <% if current_user.can_update_user?(@user.id) %>
          <div class="item">
            <%= link_to "Edit", edit_user_path(id: @user.id), class: "ui fluid green button" %>
          </div>
        <% end %>
        <% if current_user.can_destroy_users? %>
          <div class="item">
            <%= link_to "Destroy", user_path(id: @book.id), method: :delete, class: "ui fluid red button" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="ui thirteen wide column">
    <h1 class="ui header">Name: <%= "#{@user.first_name} #{@user.last_name}" %></h1>
    <% if @user.nickname %>
      <div class="ui header">Nickname: <%= @user.nickname %></div>
    <% end %>
    <div class="ui header">Birth Date: <%= @user.birth_date %></div>
  </div>
  <h2 class="ui header"><%= image_tag "books.png", class: "ui small image" %>Books</h2>
  <div class="row">
    <div class="ui link cards">
      <% @user.books.each do |book| %>
        <%= render 'books/card', {book: book} %>
      <% end %>
    </div>
  </div>
  <div class="ui divider" style="width: 100%"></div>
  <% if @borrows.length > 0 && current_user.id == @user.id %>
    <h2 class="ui header"><i class="ui skull crossbones icon"></i>Borrows</h2>
    <div class="row">
      <div class="ui link cards">
        <% @borrows.each do |borrow| %>
          <%= render 'books/card', {book: borrow.book, borrow: borrow} %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>