config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'landing#index'
  get 'landing/index'
  resources :books do
    resources :borrows, only: [:new, :create, :index, :show, :update]
    get 'reza'
  end
  resources :users do
    resources :borrows, only: [:index, :destroy, :show, :update]
  end
  resources :borrows

  namespace :users do
    get 'authors/new', action: 'new'
  end
  namespace :books do
    get 'search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  # associations
  has_many :borrows
  has_many :borrowers, through: :borrows, class_name: "User", source: "user"
  belongs_to :publisher, optional: true
  has_and_belongs_to_many :authors, class_name: "User", join_table: "authors_books"
  has_one_attached :front_cover
  has_one_attached :back_cover
  has_one_attached :sample

  # validations
  validates :isbn, format: { with: /\A\d+\z/, message: 'Please provide a valid isbn' }, length: { minimum: 10, maximum: 14 }
  validates :front_cover, :back_cover, blob: { content_type: :image }
  validates :sample, blob: { content_type: 'application/pdf' }

  def self.search(query, order, limit)
    Book.where('title like ?', query).order(order).limit(limit)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # constants
  ITEMS_PER_PAGE = 12

  # helpers
  include ApplicationHelper

  # before actions
  before_action :can_create_books?, only: [:new, :create]
  before_action :can_update_book?, only: [:edit, :update]
  before_action :crud_params, only: [:new, :create, :edit, :update]

  def index
    @pagination = {
      items_per_page: ITEMS_PER_PAGE,
      items_count: Book.all.count,
      current_page: numeric?(params[:page]) && params[:page].to_i.positive? ? params[:page].to_i : 1,
      last_page: (Book.all.count / ITEMS_PER_PAGE.to_f).ceil,
      order: params[:order_by] || 'created_at-desc'
    }
    @books = Book.order(@pagination[:order].gsub("-", " "))
                 .limit(@pagination[:items_per_page])
                 .offset((@pagination[:current_page] - 1) * @pagination[:items_per_page])
    respond_to do |format|
      format.json
      format.html
    end
  end

  def show
    @book = Book.find(params[:id])
    @borrow = @book.borrows.where(user_id: current_user.id, return_date: nil)[0] if authenticated?
  end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)
    authors = params[:book][:authors_ids].map { |id| User.find(id) }
    if @book.save
      @book.authors << authors
      @book.save
      redirect_to(@book, notice: 'Book created')
    else
      render :new, notice: 'There was a problem when editing book', error: @book.errors
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
      else
        format.html { render :edit, notice: 'There was a problem when editing book', error: @book.errors }
      end
    end
  end

  def destroy; end

  # method get
  def search
    @q_books = Book.where("title like ?", "%#{params[:q]}%").limit(5)
    render json: {
      items: @q_books.map do |item|
        {
          title: item.title,
          url: book_path(item.id),
          authors: item.authors.map { |elem| "#{elem.first_name} #{elem.last_name}" }.join(", ")
        }
      end
    }
  end

  protected

  def book_params
    params[:book][:genre] = params[:book][:genre].split(",") if params[:book][:genre].instance_of? String
    if params[:book][:authors_ids].instance_of? String
      params[:book][:authors_ids] = params[:book][:authors_ids].split(",")
    end
    params.require(:book).permit(
      :front_cover,
      :back_cover,
      :sample,
      :title,
      :isbn,
      :publication_date,
      :pages,
      :publisher_id,
      :language,
      genre: []
    )
  end

  def crud_params
    @languages = Book.select(:language).map(&:language).uniq
    @genres = Book.select(:genre).map(&:genre).flatten.uniq
    @publishers = Publisher.select(:name, :id)
    @authors = User.joins(:role).where(roles: { name: 'author' }).map do |a|
      { name: "#{a.first_name} #{a.last_name}", id: a.id }
    end
    @authors.select! { |author| author[:id] == current_user.id } if current_user.is_an_author?
  end

  def can_create_books?
    redirect_to request.referer || request.base_url unless current_user&.can_create_books?
  end

  def can_update_book?
    redirect_url = request.referer || request.base_url
    redirect_to redirect_url unless numeric?(params[:id]) && current_user&.can_update_book?(params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_is_borrowed?(book)
    book.borrows.where(user_id: current_user.id, return_date: nil).first
  end
end

app/views/books/_card.html.erb
<div class="ui card">
  <div class="image">
    <%= image_tag resource_image_url(book.front_cover) %>
  </div>
  <div class="content" style="display: flex; flex-direction: column;">
    <%= link_to "#{book.title}", book_path(book.id), class: "header" %>
    <div class="meta">
      <%= book.authors.length == 1 ? "Author" : "Author".pluralize %>:
      <% book.authors.each_with_index do |author, index| %>
        <%= link_to "#{author.first_name} #{author.last_name}#{"," unless index == book.authors.length - 1}", user_path(author.id) %>
      <% end %>
    </div>
    <div class="description">
      <%= book.summary %>
    </div>
    <div class="extra content" style="margin-top: auto">
      <% if authenticated? %>
        <% borrow = book_is_borrowed?(book) %>
        <% if borrow %>
          <small>expiration date: <%= borrow.borrow_date.weeks_since(2).to_formatted_s(:long) %></small>
          <% if (Date.today - borrow.borrow_date.weeks_since(2)).to_i > 14 %>
            <div class="ui red message">penalty: <%= (Date.today - borrow.borrow_date.weeks_since(2)).to_i * Borrow::PENALTY %>
              $
            </div>
          <% end %>
          <%= form_with(url: book_borrow_path(book_id: book.id, id: borrow.id), html: {method: :patch}, local: true) do |form| %>
            <%= form.hidden_field :return_date, value: Date.today %>
            <%= form.button "Return", class: "ui fluid #{Date.today >= borrow.borrow_date.weeks_since(2) ? "red" : "blue"} button" %>
          <% end %>
          <% if borrow %>
          <% end %>
        <% elsif current_user.can_borrow_book?(book.id) %>
          <%= form_with(url: book_borrows_path(book_id: book.id), method: "post", local: true) do |form| %>
            <%= form.submit "Borrow", class: "ui fluid violet button" %>
          <% end %>
        <% else %>
          <small>You reach maximum books borrowed. please return them to borrow more!</small>
        <% end %>
      <% else %>
        <small>Please login/sign up to borrow</small>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<div class="ui raised very padded text container segment" style="margin-top: 2rem">
  <h1 class="ui header"><%= name %></h1>
  <%= form_with(model: model, html: {class: "ui form"}) do |f| %>
    <% if model.errors.any? %>
      <div id="error_explanation">
        <div class="ui header"><%= pluralize(model.errors.count, "error") %> prohibited this Book from being saved:</div>

        <div class="ui bulleted list">
          <% model.errors.full_messages.each do |message| %>
            <div class="item ui warning message"><%= message %></div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="ui segment" style="display: flex; gap: 1rem; align-items: center">
      <%= f.label :front_cover, 'Front Cover' %>
      <%= image_tag resource_image_url(model.front_cover), class: "ui circular image", style: "margin: 0" %>
      <%= f.file_field :front_cover, accept: 'image/png,image/jpeg,image/svg+xml' %>
    </div>
    <div class="ui segment" style="display: flex; gap: 1rem; align-items: center">
      <%= f.label :back_cover, 'Back Cover' %>
      <%= image_tag resource_image_url(model.back_cover), class: "ui circular image", style: "margin: 0" %>
      <%= f.file_field :back_cover, accept: 'image/png,image/jpeg,image/svg+xml' %>
    </div>
    <div class="field">
      <%= f.label :sample, 'Sample' %>
      <%= f.file_field :sample, accept: 'application/pdf' %>
    </div>
    <div class="field">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, required: true, placeholder: 'Title' %>
    </div>
    <div class="field">
      <%= f.label :isbn, 'ISBN' %>
      <%= f.text_field :isbn, required: true, placeholder: 'Last Name', html: {minlength: 10, maxlength: 12} %>
    </div>
    <div class="field">
      <%= f.label :publication_date, 'Publication Date' %>
      <div class="ui calendar">
        <div class="ui input left icon">
          <i class="calendar icon"></i>
          <%= f.text_field :publication_date, required: true, placeholder: 'Publication Date' %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :pages, 'Pages' %>
      <%= f.number_field :pages, required: true, placeholder: 'Pages' %>
    </div>
    <div class="field">
      <%= f.label :publisher_id, 'Publisher' %>
      <div class="ui fluid search selection dropdown deny-addition">
        <%= f.hidden_field :publisher_id, required: true, placeholder: 'Publisher' %>
        <i class="dropdown icon"></i>
        <div class="default text">Publisher</div>
        <div class="menu">
          <% publishers.each do |p| %>
            <div class="item" data-value="<%= p.id %>"><%= p.name %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :genre, 'Genres' %>
      <div class="ui fluid multiple search selection dropdown allow-addition">
        <%= f.hidden_field :genre, required: true, placeholder: 'Genres' %>
        <i class="dropdown icon"></i>
        <div class="default text">Genres</div>
        <div class="menu">
          <% genres.each do |g| %>
            <div class="item" data-value="<%= g %>"><%= g %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :language, 'Language' %>
      <div class="ui fluid search selection dropdown allow-addition">
        <%= f.hidden_field :language, required: true, placeholder: 'Language' %>
        <i class="dropdown icon"></i>
        <div class="default text">Language</div>
        <div class="menu">
          <% languages.each do |l| %>
            <div class="item" data-value="<%= l %>"><%= l %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :author_id, 'Author' %>
      <div class="ui fluid search multiple selection dropdown deny-addition">
        <%= f.hidden_field :authors_ids, placeholder: 'Author' %>
        <i class="dropdown icon"></i>
        <div class="default text">Author</div>
        <div class="menu">
          <% authors.each do |a| %>
            <div class="item" data-value="<%= a[:id] %>"><%= a[:name] %></div>
          <% end %>
        </div>
      </div>
    </div>

    <%= f.submit name, class: 'ui fluid large teal submit button' %>

    <% if current_user.can_create_authors? %>
      <div class="ui message">
        Don't find author click <%= link_to 'here', users_authors_new_path, class: 'ui blue text' %> to create it
      </div>
    <% end %>
  <% end %>
</div>


<script>
    $(".ui.deny-addition.dropdown").dropdown();
    $(".ui.allow-addition.dropdown").dropdown({
        allowAdditions: true
    });
    $(".ui.calendar").calendar({type: 'date',})
</script>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<%= render 'form', name: 'Edit Book', method: "put", model: @book, languages: @languages, genres: @genres, publishers: @publishers, user: @current_user, authors: @authors %>

app/views/books/index.html.erb
<% content_for :styles do %>
  <style>
    .ui.grid > .row > .column {
      margin-bottom: 1rem !important;
    }

    .display-none {
      display: none !important;
    }

    .ui.fluid.card {
      height: 100%;
    }
  </style>
<% end %>
<div class="ui padded doubling stackable grid">
  <div class="ui row">
    <div class="ui four wide column">
      <div class="ui segment">
        <div class="ui search">
          <div class="ui left icon fluid input">
            <%= text_field_tag :search, params[:q], class: "prompt", placeholder: "Search books..." %>
            <i class="search icon"></i>
          </div>
          <div class="results"></div>
        </div>
      </div>
    </div>
    <div class="ui twelve wide column">
      <div class="ui clearing segment">
        <h1 class="ui left floated header" style="margin: 0;">Books</h1>
        <div class="ui right floated basic segment" style="margin: 0; padding: 0;">
          <div class="ui selection dropdown">
            <input type="hidden" name="order">
            <i class="dropdown icon"></i>
            <div class="default text">Order</div>
            <div class="menu">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ui row">
    <div class="ui four wide column">
    </div>
    <div class="ui twelve wide column">
      <div class="ui four column grid">
        <div class="ui row data-container">
        </div>
        <div class="ui row" style="justify-content: center;">
          <div class="ui pagination menu">
            <div class="item"><<</div>
            <div class="item">1</div>
            <div class="item">2</div>
            <div class="item">3</div>
            <div class="item">>></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    let data;
    let currentPage = <%= @pagination[:current_page] %>;
    let order = "<%= @pagination[:order] %>";
    const dataContainer = $(".data-container");
    const paginationItems = [
        $(".ui.pagination.menu .item:nth-child(1)"),
        $(".ui.pagination.menu .item:nth-child(2)"),
        $(".ui.pagination.menu .item:nth-child(3)"),
        $(".ui.pagination.menu .item:nth-child(4)"),
        $(".ui.pagination.menu .item:nth-child(5)"),
    ]
    const paginationMenu = $(".ui.pagination.menu");

    const card = (image, url, title, authors) => `
      <div class="column">
        <div class="ui fluid card">
          <div class="image">
            <img src="${image}" class="ui image" alt="cover" />
          </div>
          <div class="content">
            <a href="${url}">${_.truncate(title, {length: 24})}</a>
            <div class="meta">
              <h4 class="ui header" style="margin-top: 1rem;">${authors.length > 1 ? "Authors" : "Author"}</h4>
              <div class="ui list">
              ${authors.map(item => `
                    <a href="${item.url}" class="item">
                      <img class="ui avatar image" src="${item.avatar}" alt="avatar">
                      <div class="content">
                        <div class="description">
                          ${item.name}
                        </div>
                      </div>
                    </a>
                  `).join("")}
              </div>
          </div>
        </div>
      </div>
    `;

    async function getData(page = 1, orderBy = 'created_at-desc') {
        dataContainer.html("");

        // fetch request
        const options = {
            method: "GET",
            headers: new Headers({'content-type': 'application/json'}),
            mode: 'no-cors'
        };
        const res = await fetch(`/books?page=${page}&order_by=${orderBy}`, options);
        data = await res.json();

        // data rendering
        dataContainer.append(data["books"].map(item => card(item["image"], item["url"], item["title"], item["authors"])));
        currentPage = data["pagination"]["current_page"];
        order = data["pagination"]["order"];

        // resetting events
        if (data["pagination"]["last_page"] > 1) {
            paginationItems[1].text(data["pagination"]["current_page"] > 2 ? "..." : "1")
            paginationItems[2].text(data["pagination"]["current_page"] === 1 ? "2" : data["pagination"]["current_page"])
            paginationItems[3].text("...")
        } else {
            paginationMenu.style.display = "none"
        }
        if (currentPage <= 1) {
            paginationItems[0].addClass("disabled")
            paginationItems[1].addClass("disabled active")
            paginationItems[3].addClass("disabled")
        } else {
            paginationItems[0].removeClass("disabled")
            paginationItems[1].removeClass("disabled active")
            paginationItems[3].removeClass("disabled")
        }
        if (currentPage >= 2) {
            if (currentPage !== 2) {
                paginationItems[1].addClass("disabled")
            }
            paginationItems[2].addClass("disabled active")
            paginationItems[3].addClass("disabled")
        } else {
            paginationItems[1].removeClass("disabled")
            paginationItems[2].removeClass("disabled active")
            paginationItems[3].removeClass("disabled")
        }
        if (currentPage >= data["pagination"]["last_page"]) {
            paginationItems[3].addClass("disabled display-none")
            paginationItems[4].addClass("disabled")
        } else {
            paginationItems[3].removeClass("disabled")
            paginationItems[4].removeClass("disabled")
        }
    }

    function initEvents() {
        $(".ui.dropdown").dropdown({
            onChange: () => {
                getData(currentPage, order)
            },
            values: [
                {
                    name: 'Newest',
                    value: 'created_at-desc',
                    selected: 'created_at-desc' === order
                },
                {
                    name: 'Oldest',
                    value: 'created_at-asc',
                    selected: 'created_at-asc' === order
                }
            ]
        })
        paginationItems[0].click((e) => {
            e.preventDefault();
            getData(currentPage - 1)
        });
        paginationItems[1].click((e) => {
            e.preventDefault();
            getData(Number.parseInt(paginationItems[1].text()))
        });
        paginationItems[2].click((e) => {
            e.preventDefault();
            getData(currentPage === 1 ? 2 : currentPage)
        });
        paginationItems[3].click((e) => {
            e.preventDefault();
            getData(currentPage + 1)
        });
        paginationItems[4].click((e) => {
            e.preventDefault();
            getData(currentPage + 1)
        });
    }

    document.addEventListener("turbolinks:load", (event) => {
        event.preventDefault();
        getData(currentPage)
    })
    document.addEventListener("turbolinks:load", initEvents)
</script>

app/views/books/new.html.erb
<%= render(
        'form', {
        name: 'Create Book',
        model: @book,
        languages: @languages,
        genres: @genres,
        publishers: @publishers,
        authors: @authors
    })
%>

app/views/books/show.html.erb
<div class="ui grid container" style="padding-top: 2rem;">
  <div class="ui six wide column">
    <%= image_tag 'front-cover-placeholder.jpg', style: "width: 100%" %>
    <div class="ui list">
      <% if @book.sample.attached? %>
        <div class="item">
          <%= link_to "Download sample", url_for(@book.sample), class: "ui fluid gray button" %>
        </div>
      <% end %>
      <% if authenticated? %>
        <% if @borrow %>
          <%= form_with(url: book_borrow_path(book_id: @book.id, id: @borrow[:id]), html: {method: :patch}, local: true) do |form| %>
            <%= form.hidden_field :return_date, value: Date.today %>
            <%= form.button "Return", class: "ui fluid blue button" %>
          <% end %>
        <% elsif current_user.can_borrow_book?(@book.id) %>
          <%= form_with(url: book_borrows_path(book_id: @book.id), method: "post", local: true) do |form| %>
            <%= form.submit "Borrow", class: "ui fluid violet button" %>
          <% end %>
        <% end %>
        <% if current_user.can_update_book?(@book.id) %>
          <div class="item">
            <%= link_to "Edit", edit_book_path(id: @book.id), class: "ui fluid green button" %>
          </div>
        <% end %>
        <% if current_user.can_destroy_book?(@book.id)|| current_user.can_destroy_books? %>
          <div class="item">
            <%= link_to "Destroy", book_path(id: @book.id), method: :delete, class: "ui fluid red button" %>
          </div>
        <% end %>
      <% else %>
        <div class="center aligned item">
          <small>Please login/sign up to borrow</small>
        </div>
      <% end %>
    </div>
  </div>
  <div class="ui ten wide column">
    <h1 class="ui header"><%= @book.title %></h1>
    <h2 class="ui header"><%= @book.authors.map { |a| "#{a.first_name} #{a.last_name}" }.join(", ") %></h2>
    <div class="ui header">About the book</div>
    <div class="ui list">
      <div class="item">
        <div class="header">Pages</div>
        <%= @book.pages %>
      </div>
      <div class="item">
        <div class="header"><%= @book.genre.length > 1 ? "Genre".pluralize : "Genre" %></div>
        <%= @book.genre.join(', ') %>
      </div>
    </div>
  </div>
  <div class="ui row">
    <p class="ui text">
      <%= @book.summary %>
    </p>
  </div>
</div>