config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'landing#index'
  get 'landing/index'
  resources :books do
    resources :borrows, only: [:new, :create, :index, :show, :update]
    get 'reza'
  end
  resources :users do
    resources :borrows, only: [:index, :destroy, :show, :update]
  end
  resources :borrows

  namespace :users do
    get 'authors/new', action: 'new'
  end
  namespace :books do
    get 'search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="ui sticky">
  <div class="ui raised top attached segment">
    <div class="ui secondary menu">
      <%= link_to root_path, class: "item", target: "_top" do %>
        <%= image_tag "books.png" %>
      <% end %>

      <div class="right menu">
        <% if auth %>
          <div class="item">
            <div class="ui inline dropdown">
              <div class="text">
                <%= image_tag avatar_url(current_user&.id), class: "ui avatar image", alt: "#{user_full_name} avatar" %>
                <%= user_full_name %>
              </div>
              <i class="dropdown icon"></i>
              <div class="menu">
                <div class="item">
                  <i class="user icon"></i>
                  <%= link_to 'profile', user_path(current_user&.id) %>
                </div>
                <div class="item">
                  <i class="edit icon"></i>
                  <%= link_to 'Edit profile', edit_user_registration_path %>
                </div>
                <div class="item">
                  <i class="sign out alternate icon"></i>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div class="item">
            <div class="ui buttons">
              <%= link_to 'Login', new_user_session_path, class: 'ui secondary button' %>
              <div class="or"></div>
              <%= link_to 'Sign up', new_user_registration_path, class: 'ui primary button' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
    $(".ui.sticky").sticky({
        context: document.body
    });
    $(".ui.dropdown").dropdown()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryManagementSystem</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :styles %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="padding-top: 60px">

<div class="ui fluid secondary pointing fixed menu" style="background: white !important;">
  <%= link_to root_path, class: "item", target: "_top" do %>
    <%= image_tag "books.png" %>
  <% end %>
  <% if @current_user.signed_in? %>
    <div class="ui item header">
      Hey&nbsp;
      <%= link_to @current_user.name, user_path(@current_user.id) %>
      !
    </div>
  <% end %>
  <div class="right menu">
    <% unless @current_user.signed_in? %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'ui item' %>
      <%= link_to 'Sign In', new_user_session_path, class: 'ui item' %>
    <% else %>
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'ui item' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'ui item' %>
    <% end %>
  </div>
</div>

<div class="root">
  <%= yield %>
</div>
<% if @current_user.can_create_book? %>
  <div class="item" style="position: fixed; bottom: 1rem; right: 1rem;">
    <%= link_to new_book_path, class: "ui circular twitter icon massive button" do %>
      <i class="book icon"></i>
    <% end %>
  </div>
<% end %>

<% unless flash.empty? %>
  <script type="text/javascript">

      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      $('body')
          .toast({
              class: '<%= type %>',
              message: `<%= f[1] %>`
              , showProgress: 'bottom',
              position: 'top left',
              displayTime: 'auto',
              className: {
                  toast: 'ui message'
              },
              title: '<%= type %>',
              progressUp: true
          })
      <% end %>
  </script>
<% end %>
</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :styles %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/header', {auth: true, user_full_name: user_full_name} %>

<div class="root">
  <%= yield %>
</div>

<% if current_user.can_create_books? %>
  <div class="item" style="position: fixed; bottom: 1rem; right: 1rem;">
    <%= link_to new_book_path, class: "ui circular twitter icon massive button" do %>
      <i class="book icon"></i>
    <% end %>
  </div>
<% end %>

<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      $('body')
          .toast({
              class: '<%= type %>',
              message: `<%= f[1] %>`,
              showProgress: 'bottom',
              position: 'top left',
              displayTime: 5000,
              className: {
                  toast: 'ui message'
              },
              title: '<%= type %>',
              progressUp: true
          })
      <% end %>
  </script>
<% end %>
</body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :styles %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/header', {auth: false, user_full_name: user_full_name} %>

<div class="root">
  <%= yield %>
</div>

<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      $('body')
          .toast({
              class: '<%= type %>',
              message: `<%= f[1] %>`,
              showProgress: 'bottom',
              position: 'top left',
              displayTime: 5000,
              className: {
                  toast: 'ui message'
              },
              title: '<%= type %>',
              progressUp: true
          })
      <% end %>
  </script>
<% end %>
</body>
</html>